server:
  port: 8201
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/learning/auth/mapper/xml/*.xml,classpath:com/learning/process/mapper/xml/*.xml,classpath:com/learning/wechat/mapper/xml/*.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.212.128/zcx-oa?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.212.128
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true

wechat:
  mpAppId:
  mpAppSecret:
  userInfoUrl: http://ggkt2.vipgz1.91tunnel.com/admin/wechat/userInfo